## Singleton managing central data across application providing several functions:
## - Creates/stores PlayerData for the current run along with helper methods for retrieving common PlayerData queries.
## - Stores read only data and prototype data lookup tables with getters methods for each.
## - Maintains schema
## - Manages test data generation via add_test_x() methods
## - Stores cache of generated objects
extends Node

#region Schema and Data Management

## A lookup table used to generate other lookup tables via Global._generate_schema() and
## FileLoader._generate_base_mod_data(), which are used for schema management across the framework.
## CRITICAL: Global._generate_schema() MUST be run before any other data related methods, at the top
## of Global._ready().
## WARNING: Any time a new kind of data is added to the schema you should update this table and also run
## FileLoader._generate_base_mod_data() in _ready().
@onready var SCHEMA: Array[Array] = [
	# ["SerializableDataScriptNameAsString", SerializableDataScript, "lookup_table_property_name", ["optional external folder paths to read from", ...]],
	# read only data
	["RestActionData", RestActionData, "_id_to_rest_action_data", ["rest_actions/"]],
	["StatusEffectData", StatusEffectData, "_id_to_status_data", ["status_effects/"]],
	["ConsumableData", ConsumableData, "_id_to_consumable_data", ["consumables/"]],
	["ActData", ActData, "_id_to_act_data", ["acts/"]],
	["EventData", EventData, "_id_to_event_data", ["events/"]],
	["EventPoolData", EventPoolData, "_id_to_event_pool_data", ["event_pools/"]],
	["DialogueData", DialogueData, "_id_to_dialogue_data", ["dialogue/"]],
	["ActionInterceptorData", ActionInterceptorData, "_id_to_action_interceptor_data", ["action_interceptors/"]],
	["ColorData", ColorData, "_id_to_color_data", ["colors/"]],
	["KeywordData", KeywordData, "_id_to_keyword_data", ["keywords/"]],
	["CharacterData", CharacterData, "_id_to_character_data", ["characters/"]],
	["RunModifierData", RunModifierData, "_id_to_run_modifier_data", ["run_modifiers/"]],
	["RunStartOptionData", RunStartOptionData, "_id_to_run_start_option_data", ["run_start_options/"]],
	["CardPackData", CardPackData, "_id_to_card_pack_data", ["card_packs/"]],
	["ArtifactPackData", ArtifactPackData, "_id_to_artifact_pack_data", ["artifact_packs/"]],
	["CustomUIData", CustomUIData, "_id_to_custom_ui_data", ["custom_ui/"]],
	["CustomSignalData", CustomSignalData, "_id_to_custom_signal_data", ["custom_signals/"]],
	# prototype data
	["EnemyData", EnemyData,"_id_to_enemy_data", ["enemies/"]],
	["CardData", CardData, "_id_to_card_data", ["cards/"]],
	["ArtifactData", ArtifactData, "_id_to_artifact_data", ["artifacts/"]],
	["PlayerData", PlayerData, "_id_to_player_data", ["player/"]],
]

## These lookup tables allow for automating the process of loading, saving, and mapping data
## across the application rather than writing tons of parallel save/load/register functions.
## WARNING: This is generated by _generate_schema(). Do not manually enter into this.
var CLASS_NAME_TO_CLASS: Dictionary[String, Script] = {
	#"SerializeableData": SerializableData,
}

## Maps a SerializeableData class Script to the lookup table it corresponds to. Used for register_rod()
## WARNING: This is generated by _generate_schema(). Do not manually enter into this.
var READ_ONLY_GETTER_SCHEMA: Dictionary[Script, String] = {
	#SerializableData, "id_to_data"
}

# immutable data lookup tables. Do not modify their contents after creation
var _id_to_rest_action_data: Dictionary[String, RestActionData] = {}
var _id_to_status_data: Dictionary[String, StatusEffectData] = {}
var _id_to_consumable_data: Dictionary[String, ConsumableData] = {}
var _id_to_act_data: Dictionary[String, ActData] = {}
var _id_to_event_data: Dictionary[String, EventData] = {}
var _id_to_event_pool_data: Dictionary[String, EventPoolData] = {}
var _id_to_dialogue_data: Dictionary[String, DialogueData] = {}
var _id_to_action_interceptor_data: Dictionary[String, ActionInterceptorData] = {}
var _id_to_color_data: Dictionary[String, ColorData] = {}
var _id_to_keyword_data: Dictionary[String, KeywordData] = {}
var _id_to_character_data: Dictionary[String, CharacterData] = {}
var _id_to_run_modifier_data: Dictionary[String, RunModifierData] = {}
var _id_to_run_start_option_data: Dictionary[String, RunStartOptionData] = {}
var _id_to_card_pack_data: Dictionary[String, CardPackData] = {}
var _id_to_artifact_pack_data: Dictionary[String, ArtifactPackData] = {}
var _id_to_custom_ui_data: Dictionary[String, CustomUIData] = {}
var _id_to_custom_signal_data: Dictionary[String, CustomSignalData] = {}

# prototyped data; Read only data that are duplicated into mutable data instances
var _id_to_enemy_data: Dictionary[String, EnemyData] = {}
var _id_to_card_data: Dictionary[String, CardData] = {}
var _id_to_artifact_data: Dictionary[String, ArtifactData] = {}
var _id_to_player_data: Dictionary[String, PlayerData] = {}

# mutable data; These objects are modifiable
var player_data: PlayerData = PlayerData.new() # the current run. prototype instance.
var user_settings_data: UserSettingsData = UserSettingsData.new() # the user's settings
var profile_data: ProfileData = ProfileData.new()
var is_run: bool = false # simple flag to check if a run is currently happening

# cached objects
## Stores caches of card filter results, making complicated repeated searches across
## potentially thousands of cards more performant and organized
## These typically correspond to CardPackData object ids, but others may be added.
## See: Global._generate_card_pack_cache()
var _id_to_card_filter_cache: Dictionary[String, CardFilter] = {}

## Stores caches of artifact filter results.
## See: Global._generate_artifact_pack_cache()
var _id_to_artifact_filter_cache: Dictionary[String, ArtifactFilter] = {}

var content_database: ContentDB = null
const CORE_CONTENT_TYPES_USE_RESOURCES: bool = true

## Takes SCHEMA and generates fast lookup tables used for mapping data types
## in the framework. This automates and centralizes a lot of extremely tedious
## schema maintenance and enables useful behavior like register_rod() for test data generation,
## and file/mod loading through data table mapping.
func _generate_schema() -> void:
	for schema_row: Array in SCHEMA:
		var data_script_string: String = schema_row[0]
		var data_script: Script = schema_row[1]
		var data_lookup_table_property_name: String = schema_row[2]
		var read_only_data_folder_paths: Array[String] = []
		read_only_data_folder_paths.assign(schema_row[3])
		
		READ_ONLY_GETTER_SCHEMA[data_script] = data_lookup_table_property_name
		CLASS_NAME_TO_CLASS[data_script_string] = data_script

## Allows for automatically registering a Read-Only-Data object into its proper lookup table. This is extremely
## useful for generic data pipelines, and streamlines test data code. See READ_ONLY_GETTER_SCHEMA.
func register_rod(serializeable_data: SerializableData, allow_collisions: bool = true) -> void:
	var script_class: Script = serializeable_data.get_script() # get the type of the object
	if not READ_ONLY_GETTER_SCHEMA.has(script_class):
		breakpoint
		push_error("No lookup table for ", script_class)
		get_tree().quit()
	else:
		# find the matching lookup table of the SerializeableData
		var lookup_table_property_name: String = READ_ONLY_GETTER_SCHEMA[script_class]
		var lookup_table: Dictionary = get(lookup_table_property_name)
		if serializeable_data.object_id == "":
			breakpoint
			push_error("Empty object ID")
			get_tree().quit()
		if lookup_table.has(serializeable_data.object_id) and not allow_collisions:
			breakpoint
			push_error("Object ID collision in ", lookup_table_property_name, " for ID: ", serializeable_data.object_id)
			get_tree().quit()
		# register read only object into lookup table
		lookup_table[serializeable_data.object_id] = serializeable_data
		# reassign the lookup table to Global
		set(lookup_table_property_name, lookup_table)

#endregion

func _ready():
	### Schema
	# generate the schema. This must be done before everything else in Global or errors will ensue
	# when loading data or generating test data.
	_generate_schema()
	# make SerializableData make a mapping of global classes of its type to class.
	# this must be done before everything else or you cannot load objects from file.
	SerializableData.build_serializable_script_cache()
	
	### Load Profile and User Settings
	FileLoader.load_profile()
	FileLoader.load_user_settings()
	
	### Test data generators
	add_test_rest_actions()
	add_test_action_interceptors()
	add_test_colors()
	add_test_player_data()
	add_test_run_modifiers()
	add_test_run_start_options()
	add_test_custom_ui()
	add_test_custom_signals()
	
	_load_core_content_from_resources()
	add_test_artifact_packs()
	
	### Modding and external file loads
	#FileLoader._generate_mod_list_data() # generates the mod list used for loading ALL external files
	#FileLoader._generate_base_mod_data() # generates mod data for base game. uncomment, run once, then comment back after updating SCHEMA
	FileLoader.load_read_only_data() # loads all mods and base game exteral data
	
	### Generated from loaded data
	_apply_card_kind_rules()
	# custom signals generated from CustomSignalData
	Signals.register_all_custom_signals()
	# generate cached filters from CardPackData
	Global._generate_card_pack_cache()
	# generate cached filters from ArtifactPackData
	Global._generate_artifact_pack_cache()
	
	Global.export_content_to_resources()
	#print(Global.compare_loaded_content_with_global())
	#print(Global.get_loaded_consumables_in_segments(["common"]))
	#print(Global.get_loaded_keywords_in_segments([]))
	#print(Global.get_loaded_status_effects_in_segments(["buff"]))
	
	### Exporting Data
	# FileLoader.export_test_data() # uncomment to output all unexported test data to file

func _load_core_content_from_resources(content_root: String = "res://content") -> void:
	var loaded_content_database: ContentDB = load_content_database(content_root, true)
	_clear_core_content_tables()
	_register_core_content_table(loaded_content_database.acts_by_id)
	_register_core_content_table(loaded_content_database.events_by_id)
	_register_core_content_table(loaded_content_database.event_pools_by_id)
	_register_core_content_table(loaded_content_database.dialogues_by_id)
	_register_core_content_table(loaded_content_database.card_packs_by_id)
	_register_core_content_table(loaded_content_database.artifacts_by_id)
	_register_core_content_table(loaded_content_database.characters_by_id)
	_register_core_content_table(loaded_content_database.enemies_by_id)
	_register_core_content_table(loaded_content_database.cards_by_id)
	_register_core_content_table(loaded_content_database.keywords_by_id)
	_register_core_content_table(loaded_content_database.consumables_by_id)
	_register_core_content_table(loaded_content_database.status_effects_by_id)

func _clear_core_content_tables() -> void:
	_id_to_act_data.clear()
	_id_to_event_data.clear()
	_id_to_event_pool_data.clear()
	_id_to_dialogue_data.clear()
	_id_to_card_pack_data.clear()
	_id_to_artifact_data.clear()
	_id_to_character_data.clear()
	_id_to_enemy_data.clear()
	_id_to_card_data.clear()
	_id_to_keyword_data.clear()
	_id_to_consumable_data.clear()
	_id_to_status_data.clear()

func _register_core_content_table(content_table: Dictionary) -> void:
	for content_id: String in content_table.keys():
		var serializable_data: SerializableData = content_table[content_id]
		register_rod(serializable_data, true)

func _apply_card_kind_rules() -> void:
	for card_data: CardData in _id_to_card_data.values():
		card_data.synchronize_card_kind_rules()
		

#region Run
## Starts a new run under a given seed with a given character
func start_run(character_object_id: String, run_seed: int, difficulty_level: int = 0, custom_run_modifier_object_ids: Array[String] = []) -> void:
	start_party_run([character_object_id], run_seed, difficulty_level, custom_run_modifier_object_ids)

## Starts a new run with a shared deck/energy state across multiple characters.
func start_party_run(character_object_ids: Array[String], run_seed: int, difficulty_level: int = 0, custom_run_modifier_object_ids: Array[String] = []) -> void:
	assert(len(character_object_ids) > 0)
	var first_character_data: CharacterData = get_character_data(character_object_ids[0])
	
	# initialize player data from the first character's prototype, then overwrite the fields
	# that become shared-party state.
	player_data = get_player_data_from_prototype(first_character_data.character_player_id)
	is_run = true
	player_data.player_party_members = []
	player_data.player_deck = []
	player_data.player_draw = []
	player_data.player_discard = []
	player_data.player_hand = []
	player_data.player_exhaust = []
	player_data.player_artifact_uid_to_artifact_data = {}
	player_data.player_artifact_pack_ids = []
	player_data.reward_draft_card_pack_ids = []
	player_data.player_reward_draft_card_id_blacklist = []
	player_data.player_reward_draft_card_id_whitelist = []
	player_data.player_money = 0
	
	### Once per run data stuff
	# initialize run rng
	player_data.player_run_seed = run_seed
	
	# generate artifact pool for the run
	player_data.initialize_artifact_pool()
	
	for i: int in range(len(character_object_ids)):
		var character_object_id: String = character_object_ids[i]
		var character_data: CharacterData = get_character_data(character_object_id)
		if character_data == null:
			push_error("No CharacterData with id of ", character_object_id)
			continue
		
		var character_player_data: PlayerData = get_player_data_from_prototype(character_data.character_player_id)
		var party_member_data: PartyMemberData = PartyMemberData.new()
		party_member_data.party_member_party_index = i
		party_member_data.party_member_character_object_id = character_object_id
		party_member_data.party_member_name = character_data.character_name
		party_member_data.party_member_health = character_data.character_starting_health
		party_member_data.party_member_health_max = character_data.character_starting_health
		party_member_data.party_member_reward_draft_card_pack_ids.assign(character_data.character_starting_card_draft_card_pack_ids)
		party_member_data.party_member_reward_draft_card_id_blacklist.assign(character_player_data.player_reward_draft_card_id_blacklist.duplicate(true))
		party_member_data.party_member_reward_draft_card_id_whitelist.assign(character_player_data.player_reward_draft_card_id_whitelist.duplicate(true))
		party_member_data.party_member_rare_card_modifier_current = character_player_data.player_rare_card_modifier_current
		party_member_data.party_member_rare_card_modifier_base = character_player_data.player_rare_card_modifier_base
		party_member_data.party_member_rare_card_increment_rate = character_player_data.player_rare_card_increment_rate
		player_data.player_party_members.append(party_member_data)
		
		for card_object_id: String in character_data.character_starting_card_object_ids:
			var card_data: CardData = get_card_data_from_prototype(card_object_id)
			player_data.assign_card_owner(card_data, i)
			player_data.player_deck.append(card_data)
		
		for artifact_pack_id: String in character_data.character_starting_artifact_pack_ids:
			if not player_data.player_artifact_pack_ids.has(artifact_pack_id):
				player_data.player_artifact_pack_ids.append(artifact_pack_id)
		
		player_data.player_money += character_data.character_starting_money
		
		# add starting artifacts after the pool is initialized so they can consume from it consistently
		for artifact_id: String in character_data.character_starting_artifact_ids:
			player_data.add_artifact(artifact_id, i, character_data.object_id)
	
	player_data.synchronize_legacy_primary_member_state()
	
	# test stuff
	# add_test_cards_to_player_deck()
	# add_test_artifacts_to_player()
	add_test_consumables_to_player()
	
	player_data.player_location_id = "location_0"
	player_data.player_act = 1
	player_data.player_run_difficulty_level = difficulty_level
	
	# determine the run modifiers
	player_data.player_run_modifier_object_ids = []
	if difficulty_level > 0:
		var difficulty_amount_max: int = min(difficulty_level, len(PlayerData.DIFFICULTY_RUN_MODIFIER_OBJECT_IDS))
		player_data.player_run_modifier_object_ids = PlayerData.DIFFICULTY_RUN_MODIFIER_OBJECT_IDS.slice(0, difficulty_amount_max, 1, true)
	player_data.player_run_modifier_object_ids += custom_run_modifier_object_ids
	
	# generate world
	ActionGenerator.generate_act("act_1", true)
	
	# connect signals and generate caches
	player_data.init()
	
	# run modifiers
	perform_start_of_run_modifiers()
	
	# save immediately at start of run
	FileLoader.autosave()
	
	Signals.run_started.emit()
	Signals.map_location_selected.emit(get_player_location_data())	# simulate visiting the first location
	
	#FileLoader.test_serialization()

## Used for end_run().
enum RUN_ENDS {QUIT, LOSS, VICTORY}

## Ends the player's current run under the given status.
func end_run(run_end_state: int = RUN_ENDS.QUIT) -> void:
	match run_end_state:
		RUN_ENDS.QUIT:
			pass
		RUN_ENDS.LOSS:
			FileLoader.delete_save()
			profile_data.lose_run(player_data.player_character_object_id)
			FileLoader.save_profile()
		RUN_ENDS.VICTORY:
			FileLoader.delete_save()
			profile_data.win_run(player_data.player_character_object_id)
			FileLoader.save_profile()
	
	is_run = false
	Signals.run_ended.emit()

## Performs any custom logic for each modifier done at the very beginning of a run
func perform_start_of_run_modifiers() -> void:
	for run_modifier_object_id in Global.player_data.player_run_modifier_object_ids:
		var run_modifier_data: RunModifierData = Global.get_run_modifier_data(run_modifier_object_id)
		if run_modifier_data == null:
			push_error("No RunData with id of ", run_modifier_object_id)
		else:
			var run_modifier_modifier_script: Script = run_modifier_data.run_modifier_modifier_script
			if run_modifier_modifier_script != null:
				var run_modidifier_script_asset: Script = run_modifier_modifier_script
				var run_modifier: BaseRunModifier = run_modidifier_script_asset.new()
				run_modifier.run_start_modification()

func pause_game() -> void:
	get_tree().paused = true
	Signals.game_paused.emit()
	
func unpause_game() -> void:
	get_tree().paused = false
	Signals.game_unpaused.emit()

#endregion

## Gets the BaseCombatant representing the player character
func get_player() -> Player:
	var players: Array[Player] = get_players()
	if len(players) == 0:
		return null
	return players[0]

func get_players() -> Array[Player]:
	var players: Array[Player] = []
	for node in Global.get_tree().get_nodes_in_group("players"):
		if node is Player:
			players.append(node)
	return players

func get_living_players() -> Array[Player]:
	var living_players: Array[Player] = []
	for player: Player in get_players():
		if player.is_alive():
			living_players.append(player)
	return living_players

func get_targetable_living_players() -> Array[Player]:
	var targetable_players: Array[Player] = []
	for player: Player in get_living_players():
		if player.is_targetable_by_enemy():
			targetable_players.append(player)
	return targetable_players

func get_enemies() -> Array[Enemy]:
	var enemies: Array[Enemy] = []
	for node in Global.get_tree().get_nodes_in_group("enemies"):
		if node is Enemy:
			enemies.append(node)
	return enemies

func get_living_enemies() -> Array[Enemy]:
	var living_enemies: Array[Enemy] = []
	for enemy: Enemy in get_enemies():
		if enemy.is_alive():
			living_enemies.append(enemy)
	return living_enemies

func get_primary_living_player() -> Player:
	var living_players: Array[Player] = get_living_players()
	if len(living_players) == 0:
		return null
	return living_players[0]

func get_primary_targetable_living_player() -> Player:
	var targetable_players: Array[Player] = get_targetable_living_players()
	if len(targetable_players) == 0:
		return null
	return targetable_players[0]

func get_default_player_combatant(allow_dead_fallback: bool = true) -> Player:
	var player: Player = get_primary_living_player()
	if player != null:
		return player
	if allow_dead_fallback:
		return get_player()
	return null

func get_player_by_party_index(party_index: int) -> Player:
	for player: Player in get_players():
		if player.has_method("get_party_member_index") and player.get_party_member_index() == party_index:
			return player
	# TODO: Once combat instantiates one Player node per ally, remove this fallback.
	if party_index == 0:
		return get_player()
	return null

func get_card_owner_player(card_data: CardData) -> Player:
	if card_data != null and card_data.card_owner_party_index >= 0:
		var owner_player: Player = get_player_by_party_index(card_data.card_owner_party_index)
		if owner_player != null:
			return owner_player
	return get_player()

func get_party_member_for_combatant(combatant: BaseCombatant) -> PartyMemberData:
	if not player_data.has_party_members():
		return null
	if combatant is Player:
		return combatant.get_party_member_data()
	return null

func get_context_party_member(card_data: CardData = null, combatant: BaseCombatant = null, action: BaseAction = null) -> PartyMemberData:
	if not player_data.has_party_members():
		return null
	if action != null:
		var action_party_member: PartyMemberData = get_party_member_for_combatant(action.parent_combatant)
		if action_party_member != null:
			return action_party_member
		if action.card_play_request != null and action.card_play_request.card_data != null:
			return player_data.get_party_member_for_card(action.card_play_request.card_data)
	var combatant_party_member: PartyMemberData = get_party_member_for_combatant(combatant)
	if combatant_party_member != null:
		return combatant_party_member
	if card_data != null:
		return player_data.get_party_member_for_card(card_data)
	return player_data.get_primary_party_member()

#region Combat Stats
func get_combat_stats() -> CombatStatsData:
	# shorthand helper method
	# gets player's combat stats for this combat
	return player_data.player_current_combat_stats
	
func is_player_in_combat() -> bool:
	return player_data.player_current_combat_stats != null

func is_player_turn() -> bool:
	if player_data.player_current_combat_stats == null:
		return false # not being in combat counts as not player's turn
	return player_data.player_current_combat_stats.is_player_turn

#endregion

#region Artifacts

func get_artifact_data(artifact_id: String) -> ArtifactData:
	return _id_to_artifact_data.get(artifact_id, null)

func get_all_artifacts() -> Array[ArtifactData]:
	var all_artifacts: Array[ArtifactData] = []
	all_artifacts.assign(_id_to_artifact_data.values())
	return all_artifacts

func get_artifact_data_from_prototype(artifact_id: String) -> ArtifactData:
	# generates a copy of a given ArtifactData
	var artifact_data: ArtifactData = get_artifact_data(artifact_id)
	return artifact_data.get_prototype(true)
#endregion

#region Consumables

func get_consumable_data(consumable_object_id: String) -> ConsumableData:
	return _id_to_consumable_data.get(consumable_object_id, null)

func get_player_consumable_in_slot_index(consumable_slot_index) -> ConsumableData:
	return player_data.get_consumable_in_slot(consumable_slot_index)

func add_test_consumables_to_player() -> void:
	#player_data.player_consumable_slot_to_consumable_object_id["0"] = "consumable_heal"
	#player_data.player_consumable_slot_to_consumable_object_id["1"] = "consumable_block"
	# player_data.player_consumable_slot_to_consumable_object_id["2"] = "consumable_damaging"
	player_data.player_consumable_slot_to_consumable_object_id["2"] = "consumable_multi_damaging"
#endregion

#region Rest Actions
func add_test_rest_actions() -> void:
	# rest action
	var rest_action_rest: RestActionData = RestActionData.new("rest_action_rest")
	rest_action_rest.rest_action_name = "Rest"
	rest_action_rest.rest_action_cost_type = RestActionData.REST_ACTION_COST_TYPES.EXCLUSIVE
	rest_action_rest.rest_actions = [
		{
		Scripts.ACTION_HEAL_PERCENT: {"percentage_heal_amount": 0.40}
		}
	]
	
	register_rod(rest_action_rest)
	
	# upgrade card rest action
	var rest_action_upgrade_card: RestActionData = RestActionData.new("rest_action_upgrade_card")
	rest_action_upgrade_card.rest_action_name = "Upgrade"
	rest_action_upgrade_card.rest_action_cost_type = RestActionData.REST_ACTION_COST_TYPES.INCLUSIVE_REPEATABLE
	rest_action_upgrade_card.rest_actions = [
	{
	Scripts.ACTION_PICK_CARDS: {
		"min_card_amount": 1,
		"max_card_amount": 1,
		"card_pick_type": ActionBasePickCards.CARD_PICK_TYPES.DECK,
		"card_pick_text": "Choose up to {0} card(s) to upgrade. {1} cards selected",
		"min_cards_are_required_for_action": true,
		"random_selection": false,
		# only upgradeable cards allowed
		"validator_data": [
			{Scripts.VALIDATOR_CARD_UPGRADEABLE: {}}
		],
		"action_data": [{Scripts.ACTION_UPGRADE_CARDS: {"upgrade_parent_card": true}}]
		}
	}
	]
	
	rest_action_upgrade_card.rest_action_validators = [
		{
		Scripts.VALIDATOR_DECK_HAS_UPGRADEABLE_CARD: {}
		}
	]
	
	register_rod(rest_action_upgrade_card)
	
	# remove cards action
	var rest_action_remove_cards: RestActionData = RestActionData.new("rest_action_remove_cards")
	rest_action_remove_cards.rest_action_name = "Remove Cards"
	rest_action_remove_cards.rest_action_cost_type = RestActionData.REST_ACTION_COST_TYPES.INCLUSIVE
	rest_action_remove_cards.rest_actions = [
		{
		Scripts.ACTION_PICK_CARDS: {
			"use_parent_card": false,
			"min_card_amount": 1,
			"max_card_amount": 2,
			"min_cards_are_required_for_action": true,
			"random_selection": false,
			"card_pick_text": "Choose {0} card(s) to remove. {1} cards selected",
			"card_pick_type": ActionBasePickCards.CARD_PICK_TYPES.DECK,
			"action_data": [{Scripts.ACTION_REMOVE_CARDS_FROM_DECK: {}}]
			}
		}
	]
	rest_action_remove_cards.rest_action_validators = [
		{
		Scripts.VALIDATOR_PILE_SIZE: 
			{
			"card_pick_type": ActionBasePickCards.CARD_PICK_TYPES.DECK,
			"card_type_maximum": 4,
			"card_types": CardData.CARD_TYPES.values(),	# any card
			"invert_validation": false,
			}
		}
	]
	
	register_rod(rest_action_remove_cards)
	
	# add random consumable action
	var rest_action_add_random_consumable: RestActionData = RestActionData.new("rest_action_add_random_consumable")
	rest_action_add_random_consumable.rest_action_name = "Add Random\nConsumable"
	rest_action_add_random_consumable.rest_action_cost_type = RestActionData.REST_ACTION_COST_TYPES.EXCLUSIVE
	rest_action_add_random_consumable.rest_actions = [
		{Scripts.ACTION_ADD_CONSUMABLE: {"random_consumable": true}},
	]
	
	register_rod(rest_action_add_random_consumable)
	
	# increase damage artifact action
	# paired with corresponding artifact
	var rest_action_increase_attack_on_rest: RestActionData = RestActionData.new("rest_action_increase_attack_on_rest")
	rest_action_increase_attack_on_rest.rest_action_name = "Increase Damage"
	rest_action_increase_attack_on_rest.rest_action_cost_type = RestActionData.REST_ACTION_COST_TYPES.EXCLUSIVE
	rest_action_increase_attack_on_rest.rest_actions = [
		{Scripts.ACTION_INCREASE_ARTIFACT_CHARGE: {"artifact_id": "artifact_increase_attack_on_rest"}},
	]
	
	register_rod(rest_action_increase_attack_on_rest)
	

func get_rest_action_data(rest_action_object_id: String) -> RestActionData:
	return _id_to_rest_action_data.get(rest_action_object_id, null)
#endregion

#region Status Effects

func get_status_effect_data(status_effect_object_id: String) -> StatusEffectData:
	return _id_to_status_data.get(status_effect_object_id, null)
#endregion

#region Acts

func get_act_data(act_id: String) -> ActData:
	return _id_to_act_data[act_id]

#endregion
	
#region Events and Event Pools

func get_event_data(event_object_id: String) -> EventData:
	return _id_to_event_data.get(event_object_id, null)

func get_player_event_data() -> EventData:
	# gets the event at the player's current location
	# this will typically generate a new event at the location, via LocationData.get_location_event_object_id()
	var player_location_data: LocationData = get_player_location_data()
	var location_event_object_id: String = player_location_data.get_location_event_object_id()
	return get_event_data(location_event_object_id)

func get_event_pool_data(event_pool_object_id: String) -> EventPoolData:
	return _id_to_event_pool_data.get(event_pool_object_id, null)
	
#endregion

#region Dialogue

func get_dialogue_data(dialogue_object_id: String) -> DialogueData:
	return _id_to_dialogue_data.get(dialogue_object_id, null)

#endregion

#region Action Interceptors
func add_test_action_interceptors() -> void:
	# increases damage done by attackers
	var interceptor_damage_increase: ActionInterceptorData = ActionInterceptorData.new("interceptor_damage_increase")
	interceptor_damage_increase.action_interceptor_priority = 10000
	interceptor_damage_increase.action_interceptor_modifies_parent = true
	interceptor_damage_increase.action_interceptor_closed_cultivation_allow_self_benefit = true
	interceptor_damage_increase.action_interceptor_script = load(Scripts.INTERCEPTOR_DAMAGE_INCREASE)
	interceptor_damage_increase.action_intercepted_action_paths = [Scripts.ACTION_ATTACK, Scripts.ACTION_ATTACK_POISE]
	
	register_rod(interceptor_damage_increase)
	
	# decreases damage done by attackers
	var interceptor_weaken: ActionInterceptorData = ActionInterceptorData.new("interceptor_weaken")
	interceptor_weaken.action_interceptor_priority = 9500
	interceptor_weaken.action_interceptor_modifies_parent = true
	interceptor_weaken.action_interceptor_script = load(Scripts.INTERCEPTOR_WEAKEN)
	interceptor_weaken.action_intercepted_action_paths = [Scripts.ACTION_ATTACK, Scripts.ACTION_ATTACK_POISE]
	
	register_rod(interceptor_weaken)
	
	# increases damage done to the attacked
	var interceptor_vulnerable: ActionInterceptorData = ActionInterceptorData.new("interceptor_vulnerable")
	interceptor_vulnerable.action_interceptor_priority = 9000
	interceptor_vulnerable.action_interceptor_modifies_parent = false
	interceptor_vulnerable.action_interceptor_script = load(Scripts.INTERCEPTOR_VULNERABLE)
	interceptor_vulnerable.action_intercepted_action_paths = [Scripts.ACTION_ATTACK, Scripts.ACTION_ATTACK_POISE]
	
	register_rod(interceptor_vulnerable)
	
	# negates incoming non zero damage actions
	var interceptor_negate_damage: ActionInterceptorData = ActionInterceptorData.new("interceptor_negate_damage")
	interceptor_negate_damage.action_interceptor_priority = -10000
	interceptor_negate_damage.action_interceptor_modifies_parent = false
	interceptor_negate_damage.action_interceptor_script = load(Scripts.INTERCEPTOR_NEGATE_DAMAGE)
	interceptor_negate_damage.action_intercepted_action_paths = [Scripts.ACTION_ATTACK, Scripts.ACTION_ATTACK_POISE, Scripts.ACTION_DIRECT_DAMAGE]
	
	register_rod(interceptor_negate_damage)
	
	# rejects block reset actions
	var interceptor_preserve_block: ActionInterceptorData = ActionInterceptorData.new("interceptor_preserve_block")
	interceptor_preserve_block.action_interceptor_priority = 10000
	interceptor_preserve_block.action_interceptor_modifies_parent = false
	interceptor_preserve_block.action_interceptor_script = load(Scripts.INTERCEPTOR_PRESERVE_BLOCK)
	interceptor_preserve_block.action_intercepted_action_paths = [Scripts.ACTION_RESET_BLOCK]
	
	register_rod(interceptor_preserve_block)
	
	# rejects debuffing status actions
	var interceptor_negate_debuff: ActionInterceptorData = ActionInterceptorData.new("interceptor_negate_debuff")
	interceptor_negate_debuff.action_interceptor_priority = 10000
	interceptor_negate_debuff.action_interceptor_modifies_parent = false
	interceptor_negate_debuff.action_interceptor_script = load(Scripts.INTERCEPTOR_NEGATE_DEBUFF)
	interceptor_negate_debuff.action_intercepted_action_paths = [Scripts.ACTION_APPLY_STATUS]
	
	register_rod(interceptor_negate_debuff)

	var interceptor_evasion: ActionInterceptorData = ActionInterceptorData.new("interceptor_evasion")
	interceptor_evasion.action_interceptor_priority = 11000
	interceptor_evasion.action_interceptor_modifies_parent = false
	interceptor_evasion.action_interceptor_script = load(Scripts.INTERCEPTOR_EVASION)
	interceptor_evasion.action_intercepted_action_paths = [Scripts.ACTION_ATTACK, Scripts.ACTION_ATTACK_POISE]

	register_rod(interceptor_evasion)

	var interceptor_burn_shield_half: ActionInterceptorData = ActionInterceptorData.new("interceptor_burn_shield_half")
	interceptor_burn_shield_half.action_interceptor_priority = 10000
	interceptor_burn_shield_half.action_interceptor_modifies_parent = false
	interceptor_burn_shield_half.action_interceptor_script = load(Scripts.INTERCEPTOR_BURN_SHIELD_HALF)
	interceptor_burn_shield_half.action_intercepted_action_paths = [Scripts.ACTION_BLOCK]

	register_rod(interceptor_burn_shield_half)

	var interceptor_burn_poise_restore: ActionInterceptorData = ActionInterceptorData.new("interceptor_burn_poise_restore")
	interceptor_burn_poise_restore.action_interceptor_priority = 10000
	interceptor_burn_poise_restore.action_interceptor_modifies_parent = false
	interceptor_burn_poise_restore.action_interceptor_script = load(Scripts.INTERCEPTOR_BURN_POISE_RESTORE)
	interceptor_burn_poise_restore.action_intercepted_action_paths = [Scripts.ACTION_RESTORE_ENEMY_POISE]

	register_rod(interceptor_burn_poise_restore)
	
	# duplicates incoming card plays
	var interceptor_duplicate_card_plays: ActionInterceptorData = ActionInterceptorData.new("interceptor_duplicate_card_plays")
	interceptor_duplicate_card_plays.action_interceptor_priority = 10000
	interceptor_duplicate_card_plays.action_interceptor_modifies_parent = true
	interceptor_duplicate_card_plays.action_interceptor_script = load(Scripts.INTERCEPTOR_DUPLICATE_CARD_PLAYS)
	interceptor_duplicate_card_plays.action_intercepted_action_paths = [Scripts.ACTION_CARD_PLAY]
	
	register_rod(interceptor_duplicate_card_plays)
	
	# duplicates incoming attack card plays
	var interceptor_duplicate_attacks: ActionInterceptorData = ActionInterceptorData.new("interceptor_duplicate_attacks")
	interceptor_duplicate_attacks.action_interceptor_priority = 10000
	interceptor_duplicate_attacks.action_interceptor_modifies_parent = true
	interceptor_duplicate_attacks.action_interceptor_script = load(Scripts.INTERCEPTOR_DUPLICATE_ATTACKS)
	interceptor_duplicate_attacks.action_intercepted_action_paths = [Scripts.ACTION_CARD_PLAY]
	
	register_rod(interceptor_duplicate_attacks)

	# grants bypass_block to the next generated attack
	var interceptor_next_attack_piercing: ActionInterceptorData = ActionInterceptorData.new("interceptor_next_attack_piercing")
	interceptor_next_attack_piercing.action_interceptor_priority = 10000
	interceptor_next_attack_piercing.action_interceptor_modifies_parent = true
	interceptor_next_attack_piercing.action_interceptor_script = load(Scripts.INTERCEPTOR_NEXT_ATTACK_PIERCING)
	interceptor_next_attack_piercing.action_intercepted_action_paths = [Scripts.ACTION_ATTACK, Scripts.ACTION_ATTACK_POISE]

	register_rod(interceptor_next_attack_piercing)

	# adds flat damage to the next generated attack
	var interceptor_next_attack_damage_bonus: ActionInterceptorData = ActionInterceptorData.new("interceptor_next_attack_damage_bonus")
	interceptor_next_attack_damage_bonus.action_interceptor_priority = 10050
	interceptor_next_attack_damage_bonus.action_interceptor_modifies_parent = true
	interceptor_next_attack_damage_bonus.action_interceptor_closed_cultivation_allow_self_benefit = true
	interceptor_next_attack_damage_bonus.action_interceptor_script = load(Scripts.INTERCEPTOR_NEXT_ATTACK_DAMAGE_BONUS)
	interceptor_next_attack_damage_bonus.action_intercepted_action_paths = [Scripts.ACTION_ATTACK, Scripts.ACTION_ATTACK_POISE]

	register_rod(interceptor_next_attack_damage_bonus)

	var interceptor_next_attack_double_damage: ActionInterceptorData = ActionInterceptorData.new("interceptor_next_attack_double_damage")
	interceptor_next_attack_double_damage.action_interceptor_priority = 10060
	interceptor_next_attack_double_damage.action_interceptor_modifies_parent = true
	interceptor_next_attack_double_damage.action_interceptor_closed_cultivation_allow_self_benefit = true
	interceptor_next_attack_double_damage.action_interceptor_script = load(Scripts.INTERCEPTOR_NEXT_ATTACK_DOUBLE_DAMAGE)
	interceptor_next_attack_double_damage.action_intercepted_action_paths = [Scripts.ACTION_ATTACK, Scripts.ACTION_ATTACK_POISE]

	register_rod(interceptor_next_attack_double_damage)

	var interceptor_next_jab_damage_bonus: ActionInterceptorData = ActionInterceptorData.new("interceptor_next_jab_damage_bonus")
	interceptor_next_jab_damage_bonus.action_interceptor_priority = 10055
	interceptor_next_jab_damage_bonus.action_interceptor_modifies_parent = true
	interceptor_next_jab_damage_bonus.action_interceptor_closed_cultivation_allow_self_benefit = true
	interceptor_next_jab_damage_bonus.action_interceptor_script = load(Scripts.INTERCEPTOR_NEXT_JAB_DAMAGE_BONUS)
	interceptor_next_jab_damage_bonus.action_intercepted_action_paths = [Scripts.ACTION_ATTACK, Scripts.ACTION_ATTACK_POISE]

	register_rod(interceptor_next_jab_damage_bonus)
	

func get_action_interceptor_data(action_interceptor_object_id: String) -> ActionInterceptorData:
	return _id_to_action_interceptor_data.get(action_interceptor_object_id, null)
#endregion

#region Colors

func add_test_colors() -> void:
	var color_green: ColorData = ColorData.new("color_green")
	color_green.color = Color.WEB_GREEN
	register_rod(color_green)
	
	var color_orange: ColorData = ColorData.new("color_orange")
	color_orange.color = Color.CORAL
	register_rod(color_orange)
	
	var color_red: ColorData = ColorData.new("color_red")
	color_red.color = Color.FIREBRICK
	register_rod(color_red)
	
	var color_blue: ColorData = ColorData.new("color_blue")
	color_blue.color = Color.ROYAL_BLUE
	register_rod(color_blue)
	
	var color_white: ColorData = ColorData.new("color_white")
	color_white.color = Color.WHITE_SMOKE
	register_rod(color_white)
	
	var color_purple: ColorData = ColorData.new("color_purple")
	color_purple.color = Color.REBECCA_PURPLE
	register_rod(color_purple)

func get_color_data(color_id: String) -> ColorData:
	return _id_to_color_data.get(color_id)
#endregion

#region Keywords
func get_keyword_data(keyword_object_id: String) -> KeywordData:
	return _id_to_keyword_data.get(keyword_object_id, null)

#endregion

#region Characters

func get_character_data(character_object_id: String) -> CharacterData:
	return _id_to_character_data.get(character_object_id, null)

func get_player_character_data() -> CharacterData:
	# gets the character data that the current player is playing as
	var character_data: CharacterData = get_character_data(player_data.player_character_object_id)
	return character_data
#endregion

#region Run Modifiers

func get_run_modifier_data(run_modifier_object_id: String) -> RunModifierData:
	return _id_to_run_modifier_data.get(run_modifier_object_id, null)

func add_test_run_modifiers() -> void:
	var run_modifier_difficulty_1: RunModifierData = RunModifierData.new("run_modifier_difficulty_1")
	run_modifier_difficulty_1.run_modifier_name = "Difficulty 1 (Increased Enemy Health)"
	run_modifier_difficulty_1.run_modifier_modifier_script = load("res://scripts/run_modifiers/difficulties/RunModifierDifficulty1.gd")

	register_rod(run_modifier_difficulty_1)
	
	var run_modifier_difficulty_2: RunModifierData = RunModifierData.new("run_modifier_difficulty_2")
	run_modifier_difficulty_2.run_modifier_name = "Difficulty 2 (Increased Minibosss Health)"
	run_modifier_difficulty_2.run_modifier_modifier_script = load("res://scripts/run_modifiers/difficulties/RunModifierDifficulty2.gd")

	register_rod(run_modifier_difficulty_2)
	
	var run_modifier_difficulty_3: RunModifierData = RunModifierData.new("run_modifier_difficulty_3")
	run_modifier_difficulty_3.run_modifier_name = "Difficulty 3 (Increased Boss Health)"
	run_modifier_difficulty_3.run_modifier_modifier_script = load("res://scripts/run_modifiers/difficulties/RunModifierDifficulty3.gd")

	register_rod(run_modifier_difficulty_3)
	
	var run_modifier_difficulty_4: RunModifierData = RunModifierData.new("run_modifier_difficulty_4")
	run_modifier_difficulty_4.run_modifier_name = "Difficulty 4"
	run_modifier_difficulty_4.run_modifier_modifier_script = load("res://scripts/run_modifiers/difficulties/RunModifierDifficulty4.gd")

	register_rod(run_modifier_difficulty_4)
	
	var run_modifier_difficulty_5: RunModifierData = RunModifierData.new("run_modifier_difficulty_5")
	run_modifier_difficulty_5.run_modifier_name = "Difficulty 5"
	run_modifier_difficulty_5.run_modifier_modifier_script = load("res://scripts/run_modifiers/difficulties/RunModifierDifficulty5.gd")

	register_rod(run_modifier_difficulty_5)
	
	### Custom Run Modifiers
	var run_modifier_custom_easy_mode: RunModifierData = RunModifierData.new("run_modifier_custom_easy_mode")
	run_modifier_custom_easy_mode.run_modifier_name = "Easy Mode"
	run_modifier_custom_easy_mode.run_modifier_description = "All enemies are set to 1HP"
	run_modifier_custom_easy_mode.run_modifier_is_custom =  true
	run_modifier_custom_easy_mode.run_modifier_exclusive_to_modifier_ids = []
	run_modifier_custom_easy_mode.run_modifier_modifier_script = load("res://scripts/run_modifiers/custom/RunModifierCustomEasyMode.gd")

	register_rod(run_modifier_custom_easy_mode)
	
	var run_modifier_endless_mode: RunModifierData = RunModifierData.new("run_modifier_endless_mode")
	run_modifier_endless_mode.run_modifier_name = "Endless Mode"
	run_modifier_endless_mode.run_modifier_description = "Run will only end when the player dies"
	run_modifier_endless_mode.run_modifier_is_custom =  true
	run_modifier_endless_mode.run_modifier_exclusive_to_modifier_ids = []
	run_modifier_endless_mode.run_modifier_modifier_script = load("res://scripts/run_modifiers/custom/RunModifierCustomEndlessMode.gd")

	register_rod(run_modifier_endless_mode)
	
	var run_modifier_custom_1: RunModifierData = RunModifierData.new("run_modifier_custom_1")
	run_modifier_custom_1.run_modifier_name = "Custom 1"
	run_modifier_custom_1.run_modifier_description = "Dummy modifier. Mutually exclusive with Custom 2"
	run_modifier_custom_1.run_modifier_is_custom =  true
	run_modifier_custom_1.run_modifier_exclusive_to_modifier_ids = ["run_modifier_custom_2"]
	run_modifier_custom_1.run_modifier_modifier_script = load("res://scripts/run_modifiers/custom/RunModifierCustom1.gd")

	register_rod(run_modifier_custom_1)
	
	var run_modifier_custom_2: RunModifierData = RunModifierData.new("run_modifier_custom_2")
	run_modifier_custom_2.run_modifier_name = "Custom 2"
	run_modifier_custom_2.run_modifier_description = "Dummy modifier. Mutually exclusive with Custom 1"
	run_modifier_custom_2.run_modifier_is_custom =  true
	run_modifier_custom_2.run_modifier_exclusive_to_modifier_ids = ["run_modifier_custom_1"]
	run_modifier_custom_2.run_modifier_modifier_script = load("res://scripts/run_modifiers/custom/RunModifierCustom2.gd")

	register_rod(run_modifier_custom_2)
		
	var run_modifier_draft_all_colors: RunModifierData = RunModifierData.new("run_modifier_draft_all_colors")
	run_modifier_draft_all_colors.run_modifier_name = "Prismatic"
	run_modifier_draft_all_colors.run_modifier_description = "Draft all card colors"
	run_modifier_draft_all_colors.run_modifier_is_custom =  true
	run_modifier_draft_all_colors.run_modifier_exclusive_to_modifier_ids = []
	run_modifier_draft_all_colors.run_modifier_modifier_script = load("res://scripts/run_modifiers/custom/RunModifierCustomDraftAllColors.gd")

	register_rod(run_modifier_draft_all_colors)
	
#endregion

#region Run Start Options
func get_run_start_option_data(run_start_option_object_id: String) -> RunStartOptionData:
	return _id_to_run_start_option_data.get(run_start_option_object_id, null)

func add_test_run_start_options() -> void:
	### Downsides
	# remove max hp
	var run_start_option_reduce_max_hp: RunStartOptionData = RunStartOptionData.new("run_start_option_reduce_max_hp")
	run_start_option_reduce_max_hp.run_start_option_bb_code = "[color=red]Lose 10 Max HP[/color]"
	run_start_option_reduce_max_hp.run_start_option_type = RunStartOptionData.RUN_START_OPTION_TYPES.PARTIAL_DOWNSIDE
	run_start_option_reduce_max_hp.run_start_option_actions = [{Scripts.ACTION_ADD_HEALTH: {"health_max_amount": -10}}]
	
	register_rod(run_start_option_reduce_max_hp)
	
	# take damage
	var run_start_option_take_damage: RunStartOptionData = RunStartOptionData.new("run_start_option_take_damage")
	run_start_option_take_damage.run_start_option_bb_code = "[color=red]Lose 5 HP[/color]"
	run_start_option_take_damage.run_start_option_type = RunStartOptionData.RUN_START_OPTION_TYPES.PARTIAL_DOWNSIDE
	run_start_option_take_damage.run_start_option_actions = [{Scripts.ACTION_ADD_HEALTH: {"health_amount": -5}}]

	register_rod(run_start_option_take_damage)
	
	# lose all money
	var run_start_option_lose_money: RunStartOptionData = RunStartOptionData.new("run_start_option_lose_money")
	run_start_option_lose_money.run_start_option_bb_code = "[color=red]Lose all money[/color]"
	run_start_option_lose_money.run_start_option_type = RunStartOptionData.RUN_START_OPTION_TYPES.PARTIAL_DOWNSIDE
	run_start_option_lose_money.run_start_option_actions = [{Scripts.ACTION_ADD_MONEY: {"money_amount": -1000}}]

	register_rod(run_start_option_lose_money)
	
	
	### Upsides
	# add money
	var run_start_option_add_money: RunStartOptionData = RunStartOptionData.new("run_start_option_add_money")
	run_start_option_add_money.run_start_option_bb_code = "[color=green]Gain 50 money[/color]"
	run_start_option_add_money.run_start_option_type = RunStartOptionData.RUN_START_OPTION_TYPES.PARTIAL_UPSIDE
	run_start_option_add_money.run_start_option_actions = [{Scripts.ACTION_ADD_MONEY: {"money_amount": 50}}]

	register_rod(run_start_option_add_money)
	
	# gain max hp
	var run_start_option_gain_max_hp: RunStartOptionData = RunStartOptionData.new("run_start_option_gain_max_hp")
	run_start_option_gain_max_hp.run_start_option_bb_code = "[color=green]Gain 10 Max HP[/color]"
	run_start_option_gain_max_hp.run_start_option_type = RunStartOptionData.RUN_START_OPTION_TYPES.PARTIAL_UPSIDE
	run_start_option_gain_max_hp.run_start_option_actions = [{Scripts.ACTION_ADD_HEALTH: {"health_amount": 10, "health_max_amount": 10}}]
	
	register_rod(run_start_option_gain_max_hp)
	
	# draft a card from player's pool
	# functions identically to a standard draft
	var run_start_option_draft_card: RunStartOptionData = RunStartOptionData.new("run_start_option_draft_card")
	run_start_option_draft_card.run_start_option_bb_code = "[color=green]Draft a card[/color]"
	run_start_option_draft_card.run_start_option_type = RunStartOptionData.RUN_START_OPTION_TYPES.PARTIAL_UPSIDE
	run_start_option_draft_card.run_start_option_actions = [
		{
		Scripts.ACTION_PICK_CARDS: {
			"card_pick_type": ActionBasePickCards.CARD_PICK_TYPES.DRAFT,
			"pick_draft_cards": false,
			"draft_from_card_pool": true,
			"action_data": [{Scripts.ACTION_ADD_CARDS_TO_DECK: {}}],
			# use same rng as player drafting so it counts as draft
			"rng_name": "rng_card_drafting",
			"validator_data": [], # this should always be empty if draft_use_player_draft = true
			# weighted draft from player draft pool with pity system
			"draft_use_player_draft": true,
			"draft_is_weighted": false,
			"draft_use_pity_system": false,
			}
		}
	]
	
	register_rod(run_start_option_draft_card)
	
	# draft common card available to the player
	# this uses validators to scan the entire card pool for a draft
	# you could also use a card pack to achieve a similar effect
	var run_start_option_draft_common_card: RunStartOptionData = RunStartOptionData.new("run_start_option_draft_common_card")
	run_start_option_draft_common_card.run_start_option_bb_code = "[color=green]Draft a common card[/color]"
	run_start_option_draft_common_card.run_start_option_type = RunStartOptionData.RUN_START_OPTION_TYPES.PARTIAL_UPSIDE
	run_start_option_draft_common_card.run_start_option_actions = [
		{
		Scripts.ACTION_PICK_CARDS: {
			"card_pick_type": ActionBasePickCards.CARD_PICK_TYPES.DRAFT,
			"pick_draft_cards": false,
			"draft_from_card_pool": true,
			"action_data": [{Scripts.ACTION_ADD_CARDS_TO_DECK: {}}],
			"validator_data": [
				{Scripts.VALIDATOR_CARD_RARITY: {"card_rarities": [CardData.CARD_RARITIES.COMMON]}},
				{Scripts.VALIDATOR_CARD_DRAFTABLE: {}},
			],
			# use same rng as player drafting so it counts as draft
			"rng_name": "rng_card_drafting",
			"draft_use_player_draft": false, # this should always be false if using a validator based draft
			"draft_is_weighted": false,
			"draft_use_pity_system": false,
			}
		}
	]
	
	register_rod(run_start_option_draft_common_card)
	
	# draft a colorless card from the white card pack
	var run_start_option_draft_colorless_card: RunStartOptionData = RunStartOptionData.new("run_start_option_draft_colorless_card")
	run_start_option_draft_colorless_card.run_start_option_bb_code = "[color=green]Draft a colorless card[/color]"
	run_start_option_draft_colorless_card.run_start_option_type = RunStartOptionData.RUN_START_OPTION_TYPES.PARTIAL_UPSIDE
	run_start_option_draft_colorless_card.run_start_option_actions = [
		{
		Scripts.ACTION_PICK_CARDS: {
			"card_pick_type": ActionBasePickCards.CARD_PICK_TYPES.DRAFT,
			"pick_draft_cards": false,
			"draft_from_card_pool": true,
			"action_data": [{Scripts.ACTION_ADD_CARDS_TO_DECK: {}}],
			"validator_data": [],
			# use same rng as player drafting so it counts as draft
			"rng_name": "rng_card_drafting",
			# get white cards
			"draft_card_pack_id": "card_pack_white"
			}
		}
	]
	
	register_rod(run_start_option_draft_colorless_card)
	
	### Complete
	
	# replace the primary character's starting passive/artifact slot with a random boss artifact
	var run_start_option_artifact_swap: RunStartOptionData = RunStartOptionData.new("run_start_option_artifact_swap")
	run_start_option_artifact_swap.run_start_option_bb_code = "[color=green]Replace Starting Passive With Boss Artifact[/color]"
	run_start_option_artifact_swap.run_start_option_type = RunStartOptionData.RUN_START_OPTION_TYPES.COMPLETE
	run_start_option_artifact_swap.run_start_option_actions = [{Scripts.ACTION_SWAP_BOSS_ARTIFACT: {}}]
	
	register_rod(run_start_option_artifact_swap)
	
#endregion

#region Custom UI
func get_custom_ui_data(custom_ui_object_id: String) -> CustomUIData:
	return _id_to_custom_ui_data.get(custom_ui_object_id, null)

func add_test_custom_ui() -> void:
	var custom_ui_see_top_of_draw_pile: CustomUIData = CustomUIData.new("custom_ui_see_top_of_draw_pile")
	custom_ui_see_top_of_draw_pile.custom_ui_asset_path = "res://scenes/ui/custom/CustomUISeeTopOfDrawPile.tscn"
	# custom_ui_see_top_of_draw_pile.custom_ui_requires_target = true
	register_rod(custom_ui_see_top_of_draw_pile)

#endregion

#region Custom UI
func get_custom_signal_data(custom_signal_object_id: String) -> CustomSignalData:
	return _id_to_custom_signal_data.get(custom_signal_object_id, null)

func add_test_custom_signals() -> void:
	var custom_signal_special_discard: CustomSignalData = CustomSignalData.new("custom_signal_special_discard")
	custom_signal_special_discard.custom_signal_is_stat = true
	custom_signal_special_discard.custom_signal_stat_name = "CUSTOM_STAT_SPECIAL_DISCARD"
	register_rod(custom_signal_special_discard)

#endregion

#region Locations

func get_location_data(location_id: String) -> LocationData:
	return player_data.location_id_to_location_data.get(location_id, null)

func get_all_locations() -> Array[LocationData]:
	var locations: Array[LocationData] = []
	for location in player_data.location_id_to_location_data.values():
		locations.append(location)
	return locations

func get_all_act_locations() -> Array[LocationData]:
	# gets all locations in the player's act
	var locations: Array[LocationData] = []
	for location in player_data.location_id_to_location_data.values():
		if location.location_act == player_data.player_act:
			locations.append(location)
	return locations

func get_player_location_data() -> LocationData:
	return get_location_data(player_data.player_location_id)

func get_next_locations(location_id: String = player_data.player_location_id) -> Array[LocationData]:
	# helper method to get the locations after a given one
	# defaults to player's location
	var next_locations: Array[LocationData] = []
	
	var current_location_data: LocationData = get_location_data(location_id)
	
	if current_location_data == null:
		breakpoint
		return []
		
	for next_location_id in current_location_data.location_next_location_ids:
		var next_location_data: LocationData = get_location_data(next_location_id)
		next_locations.append(next_location_data)
	
	return next_locations

func is_end_of_act() -> bool:
	return len(get_next_locations()) == 0

## Returns whether the run should end or not
func is_end_of_run() -> bool:
	if not is_end_of_act():
		return false # more locations ahead
	if player_data.player_act_max <= 0:
		return false # endless mode
	if player_data.player_act < player_data.player_act_max:
		return false # more acts ahead
	return true

func clear_locations() -> void:
	player_data.location_id_to_location_data.clear()
#endregion

#region Shops

## Creates a new shop and assigns it the player's location
func generate_shop_at_player_location() -> ShopData:
	var location_data: LocationData = Global.get_player_location_data()
	var shop_data: ShopData = ShopData.new()
	shop_data.shop_location_id = location_data.location_id
	player_data.player_shop_data = shop_data
	return shop_data
	
## Gets the player's shop data if the shop matches the player data. This is used to check against
## old shops at a previous location.
func get_shop_at_player_location() -> ShopData:
	var player_shop_data: ShopData = Global.player_data.player_shop_data
	var player_location_data: LocationData = get_player_location_data()
	# no shop
	if player_shop_data == null:
		return null
	# shop not at current location
	if player_shop_data.shop_location_id != player_location_data.location_id:
		return null
	
	return player_shop_data

#endregion

#region Enemies

func get_enemy_data(enemy_object_id: String) -> EnemyData:
	return _id_to_enemy_data.get(enemy_object_id, null)
	
func get_enemy_data_from_prototype(enemy_object_id: String) -> EnemyData:
	# generates a copy of a given EnemyData
	var enemy_data: EnemyData = get_enemy_data(enemy_object_id)
	return enemy_data.get_prototype(true)

#endregion


#region Player Data Prototypes

func add_test_player_data() -> void:
	var player_red: PlayerData = PlayerData.new("player_red")
	player_red.player_character_object_id = "character_red"
	
	register_rod(player_red)
	
	var player_blue: PlayerData = PlayerData.new("player_blue")
	player_blue.player_character_object_id = "character_blue"
	
	register_rod(player_blue)
	
	var player_green: PlayerData = PlayerData.new("player_green")
	player_green.player_character_object_id = "character_green"
	
	register_rod(player_green)
	
	var player_orange: PlayerData = PlayerData.new("player_orange")
	player_orange.player_character_object_id = "character_orange"
	
	register_rod(player_orange)

	var player_ranger: PlayerData = PlayerData.new("player_ranger")
	player_ranger.player_character_object_id = "character_ranger"
	
	register_rod(player_ranger)

	var player_mercenary: PlayerData = PlayerData.new("player_mercenary")
	player_mercenary.player_character_object_id = "character_mercenary"
	
	register_rod(player_mercenary)

	var player_samurai: PlayerData = PlayerData.new("player_samurai")
	player_samurai.player_character_object_id = "character_samurai"
	
	register_rod(player_samurai)

	var player_monk: PlayerData = PlayerData.new("player_monk")
	player_monk.player_character_object_id = "character_monk"
	
	register_rod(player_monk)

func get_player_data_from_prototype(player_id: String) -> PlayerData:
	var _player_data: PlayerData = _id_to_player_data[player_id]
	return _player_data.get_prototype(true)

#endregion

#region Cards

## Gets the data of a read only card data template.
## Use get_card_data_from_prototype() to make an editable copy
func get_card_data(card_object_id: String) -> CardData:
	
	return _id_to_card_data.get(card_object_id, null)

func get_all_cards() -> Array[CardData]:
	var all_cards: Array[CardData] = []
	for card_data in _id_to_card_data.values():
		all_cards.append(card_data)
	return all_cards

## Generates a mutable copy of a given read only CardData
func get_card_data_from_prototype(card_object_id: String) -> CardData:
	var card_data: CardData = get_card_data(card_object_id)
	return card_data.get_prototype(true)

## Gets mutable copies of CardData given read only CardData ids
func get_card_data_from_prototypes(card_object_ids: Array[String]) -> Array[CardData]:
	var card_prototypes: Array[CardData] = []
	for card_object_id: String in card_object_ids:
		card_prototypes.append(get_card_data_from_prototype(card_object_id))
	return card_prototypes

#endregion

#region Card Packs

func get_card_pack_data(card_pack_object_id: String) -> CardPackData:
	return _id_to_card_pack_data.get(card_pack_object_id, null)

#endregion
#region Artifact Packs

func get_artifact_pack_data(artifact_pack_object_id: String) -> ArtifactPackData:
	return _id_to_artifact_pack_data.get(artifact_pack_object_id, null)

func add_test_artifact_packs() -> void:
	# all artifacts in game, with no filtering
	var artifact_pack_all: ArtifactPackData = ArtifactPackData.new("artifact_pack_all")
	artifact_pack_all.exclude_non_standard_rarities = false
	register_rod(artifact_pack_all)
	
	# common pool artifacts, ignoring non-standard types and rarities
	# all characters should have this and their color by default
	var artifact_pack_white: ArtifactPackData = ArtifactPackData.new("artifact_pack_white")
	artifact_pack_white.artifact_pack_color_id = "color_white"
	register_rod(artifact_pack_white)
	
	var artifact_pack_red: ArtifactPackData = ArtifactPackData.new("artifact_pack_red")
	artifact_pack_red.artifact_pack_color_id = "color_red"
	register_rod(artifact_pack_red)
	
	var artifact_pack_blue: ArtifactPackData = ArtifactPackData.new("artifact_pack_blue")
	artifact_pack_blue.artifact_pack_color_id = "color_blue"
	register_rod(artifact_pack_blue)
	
	var artifact_pack_green: ArtifactPackData = ArtifactPackData.new("artifact_pack_green")
	artifact_pack_green.artifact_pack_color_id = "color_green"
	register_rod(artifact_pack_green)
	
	var artifact_pack_orange: ArtifactPackData = ArtifactPackData.new("artifact_pack_orange")
	artifact_pack_orange.artifact_pack_color_id = "color_orange"
	register_rod(artifact_pack_orange)


#endregion


#region Caches

## Uses all loaded CardPackData to generate CardFilters and store them in a cache for reuse. This is
## typically only called once on game start.
func _generate_card_pack_cache() -> void:
	for card_pack_data: CardPackData in Global._id_to_card_pack_data.values():
		var card_filter: CardFilter = card_pack_data.create_card_pack_card_filter()
		card_filter.cache_filter(card_pack_data.object_id)

## NOTE: This method should always be called from CardFilter.cache_filter()
## The ID will typically be the same as a card pack ID, but if card filters are cached from other places
## specific IDs can be added ad hoc.
func cache_card_filter(card_filter_cache_id: String, card_filter: CardFilter) -> void:
	_id_to_card_filter_cache[card_filter_cache_id] = card_filter

func get_cached_card_filter(card_filter_cache_id: String) -> CardFilter:
	return _id_to_card_filter_cache.get(card_filter_cache_id, null)

## Uses all loaded ArtifactPackData to generate ArtifactFilters and store them in a cache for reuse. This is
## typically only called once on game start.
func _generate_artifact_pack_cache() -> void:
	for artifact_pack_data: ArtifactPackData in Global._id_to_artifact_pack_data.values():
		var artifact_filter: ArtifactFilter = artifact_pack_data.create_artifact_pack_artifact_filter()
		artifact_filter.cache_filter(artifact_pack_data.object_id)

## NOTE: This method should always be called from ArtifactFilter.cache_filter()
## The ID will typically be the same as a artifact pack ID, but if artifact filters are cached from other places
## specific IDs can be added ad hoc.
func cache_artifact_filter(artifact_filter_cache_id: String, artifact_filter: ArtifactFilter) -> void:
	_id_to_artifact_filter_cache[artifact_filter_cache_id] = artifact_filter

func get_cached_artifact_filter(artifact_filter_cache_id: String) -> ArtifactFilter:
	return _id_to_artifact_filter_cache.get(artifact_filter_cache_id, null)

#endregion

#region General Utility

## Returns if all given validators pass. This is used all across framework.
func validate(validators: Array[Dictionary], card_data: CardData = null, action: BaseAction = null, context_values: Dictionary[String, Variant] = {}) -> bool:
	for validator_data: Dictionary in validators:
		for validator_token: String in validator_data:
			var validator_script_asset: Script = Scripts.resolve_script(validator_token)
			if validator_script_asset == null:
				push_error("Global.validate: Failed to resolve validator script token/path: %s" % validator_token)
				return false
			var validator: BaseValidator = validator_script_asset.new()
			
			var validator_values: Dictionary[String, Variant] = {}
			validator_values.assign(validator_data[validator_token]) # assign to force typed dict
			for key: Variant in context_values.keys():
				validator_values[key] = context_values[key]
			
			if not validator.validate(card_data, action, validator_values):
				return false
	
	return true

func load_content_database(content_root: String = "res://content", force_reload: bool = false) -> ContentDB:
	if content_database != null and not force_reload:
		return content_database
	content_database = ContentDB.new()
	content_database.load_from_directory(content_root)
	return content_database

func compare_loaded_content_with_global(content_root: String = "res://content", force_reload: bool = false) -> Dictionary:
	var loaded_content_database: ContentDB = load_content_database(content_root, force_reload)
	return loaded_content_database.compare_against_global()

func get_loaded_cards_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[CardData]:
	return load_content_database(content_root).get_cards_in_segments(required_segments)

func get_loaded_acts_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[ActData]:
	return load_content_database(content_root).get_acts_in_segments(required_segments)

func get_loaded_events_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[EventData]:
	return load_content_database(content_root).get_events_in_segments(required_segments)

func get_loaded_event_pools_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[EventPoolData]:
	return load_content_database(content_root).get_event_pools_in_segments(required_segments)

func get_loaded_dialogues_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[DialogueData]:
	return load_content_database(content_root).get_dialogues_in_segments(required_segments)

func get_loaded_card_packs_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[CardPackData]:
	return load_content_database(content_root).get_card_packs_in_segments(required_segments)

func get_loaded_artifacts_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[ArtifactData]:
	return load_content_database(content_root).get_artifacts_in_segments(required_segments)

func get_loaded_enemies_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[EnemyData]:
	return load_content_database(content_root).get_enemies_in_segments(required_segments)

func get_loaded_keywords_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[KeywordData]:
	return load_content_database(content_root).get_keywords_in_segments(required_segments)

func get_loaded_consumables_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[ConsumableData]:
	return load_content_database(content_root).get_consumables_in_segments(required_segments)

func get_loaded_status_effects_in_segments(required_segments: Array[String], content_root: String = "res://content") -> Array[StatusEffectData]:
	return load_content_database(content_root).get_status_effects_in_segments(required_segments)

func get_loaded_character_cards(character_name: String, tier: String, content_root: String = "res://content") -> Array[CardData]:
	return load_content_database(content_root).get_character_cards(character_name, tier)

func get_loaded_act_enemies(act_name: String, encounter_tier: String, content_root: String = "res://content") -> Array[EnemyData]:
	return load_content_database(content_root).get_act_enemies(act_name, encounter_tier)

func export_content_to_resources(content_root: String = "res://content") -> Dictionary:
	return ContentExporter.export_all_content(content_root)

#endregion
